# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mozi_simu_sdk.comm.GRPCServerBase_pb2 as GRPCServerBase__pb2


class gRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrpcConnect = channel.unary_unary(
                '/GRPC.gRPC/GrpcConnect',
                request_serializer=GRPCServerBase__pb2.GrpcRequest.SerializeToString,
                response_deserializer=GRPCServerBase__pb2.GrpcReply.FromString,
                )
        self.GrpcConnectStream = channel.unary_stream(
                '/GRPC.gRPC/GrpcConnectStream',
                request_serializer=GRPCServerBase__pb2.GrpcRequest.SerializeToString,
                response_deserializer=GRPCServerBase__pb2.GrpcReply.FromString,
                )


class gRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GrpcConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrpcConnectStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GrpcConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.GrpcConnect,
                    request_deserializer=GRPCServerBase__pb2.GrpcRequest.FromString,
                    response_serializer=GRPCServerBase__pb2.GrpcReply.SerializeToString,
            ),
            'GrpcConnectStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GrpcConnectStream,
                    request_deserializer=GRPCServerBase__pb2.GrpcRequest.FromString,
                    response_serializer=GRPCServerBase__pb2.GrpcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPC.gRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GrpcConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPC.gRPC/GrpcConnect',
            GRPCServerBase__pb2.GrpcRequest.SerializeToString,
            GRPCServerBase__pb2.GrpcReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrpcConnectStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/GRPC.gRPC/GrpcConnectStream',
            GRPCServerBase__pb2.GrpcRequest.SerializeToString,
            GRPCServerBase__pb2.GrpcReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
